{
 "title": "DIANE",
 "description": "Information about the DIANE application.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Application Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "whois worker - upcoming expiry",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "expr": "diane_whois_worker_domain_expiry{unit=\"days\", domain!~\"example.*\"} < 2048",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "whois worker - expiring soon",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "diane_whois_worker_domain_expiry{unit=\"days\", domain!~\"example.*\"} < 2048"
    }
   ]
  },
  {
   "title": "whois client - latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (refer) (\nrate(diane_whois_client_command_duration_seconds_sum[15m]) / \nrate(diane_whois_client_command_duration_seconds_count[15m])\n)",
     "legendFormat": "{{refer}}"
    }
   ]
  },
  {
   "title": "whois client - query result status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (status) (diane_whois_client_command_duration_seconds_count)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "whois client - anomalies",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "count by (target, status) (diane_whois_client_command_duration_seconds_count{status!=\"OK\"})"
    }
   ]
  },
  {
   "title": "whois worker - channel queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
   "targets": [
    { "expr": "diane_whois_worker_channel", "legendFormat": "{{type}}" }
   ]
  },
  { "title": "Go Process Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "diane_version_info", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Go Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}} - resident" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}} - virtual" }
   ]
  },
  {
   "title": "Process CPU Seconds over 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Go Open FDS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}} - bytes allocated" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s])",
     "legendFormat": "{{job}} - alloc rate"
    },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "{{job}} - stack inuse" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{job}} - heap inuse" }
   ]
  }
 ]
}